AlexNisnevich/untrusted

- solutions/17_pointers.md
solution with a redefine shuffle
> add a solution

- solutions/20_bossFight.md
Please merge commits because I think this is an awesome solution.
Thank you to those who have posted solutions before I do.  Without your solutions, I would never have been able to understand the code and create this awesome solution.
> Added solution: Use a boss the fight a boss

- solutions/06_drones101.md
This is a new solution which uses slightly fewer lines of code than solution 1.
> You can use map.createFromGrid()

- solutions/04_multiplicity.md
Alternative solution to Level 4 (multiplicity): Use an if() statement to stop walls from being created.
> Level 4 (multiplicity): Alternative solution

- index.html
Add noscript tag and message to help in detecting problems on the client side.
> Add no script tag

- index.html
Here's what I think would be an improved `<noscript>` message, as well as some spaces to tabs formatting improvements that I couldn't ignore. Let me know if I should split these into two pull requests. Cheers.
> improved noscript message and formatting

- solutions/01_cellBlockA.md
- solutions/11_robot.md
Just some additional/alternate solutions.
In each file, I tried to maintain the existing formatting.
> Additional solutions

- solutions/bonus/01_inTheDesert.md
- solutions/bonus/02_theEmptyRoom.md
- solutions/bonus/threeKeys.md
There should be a solutions folder for the bonus levels, like with the regular levels.
> Bonus Level Solution Folder

- solutions/06_drones101.md
- solutions/bonus/wallsWithEyes.md
Oh, you place a single block and move around it to lose the drone.
> New minimalistic solution (for drones101.jsx)

- solutions/20_bossFight.md
didn't see any solutions like this. it's probably not in the spirit of the game, but it certainly does back up the motif of hacking the game to bits.
> new solution for 20

- solutions/07_colors.md
> add solution to level 7

- solutions/14_crispsContest.md
I don't think there was one that had quite the same approach as this. Feel free to close if you think it's a duplicate, but I thought it was a creative way to do it!
> add solution to level 14

- solutions/20_bossFight.md
Why not just return bullets to boss?
Also added missing code closing tag.
> Added simple solution for lvl 20 + small fix.

- solutions/07_colors.md
I came up with a few, but this was my favourite.
> Add solution for level 7

- scripts/map.js
> Validate timer callbacks

- scripts/validate.js
> Prevent tampering with validateLevel and onExit

- solutions/20_bossFight.md
This "hack the game" solution was patched by me in #434, and no longer works.
> Remove solution to level 20

- solutions/20_bossFight.md
This was broken by a28802149c2af44bf7e8b41e87f70b56fd7c4895. While I'm fairly sure this could be rewritten to get around that patch, it doesn't work right now, so should be removed.
> Remove another patched solution to level 20

- scripts/game.js
- scripts/map.js
- scripts/validate.js
> Make detectTampering far more robust

- index.html
- scripts/game.js
- scripts/validate.js
- solutions/20_bossFight.md
Instead of trying to prohibit user code from accessing bad functions, simply run the code in a restricted sandbox that doesn't have access to those functions.
Fixes part of #215 (the report given in the first comment no longer works, but the alternate solution by @ChALkeR still does); Fixes #214; Fixes #188;  Fixes #175;  Fixes a lot of other security problems that nobody else bothered to report.
> Run user code in an iframe for extra security

- scripts/display.js
- scripts/map.js
> Make getDynamicObjects return a copy of the dynamic object list

- README.md
- levels/20_bossFight.jsx
- levels/bonus/soccer.jsx
- scripts/dynamicObject.js
- scripts/game.js
- scripts/map.js
- scripts/player.js
- scripts/validate.js
> Prevent tampering instead of detecting it

- scripts/validate.js
This has been broken ever since I changed the code to use an iframe,
since the SyntaxError thrown from evaluating code in the iframe is not
the same as the SyntaxError in the parent frame.
Also made it run the code in strict mode so strict-mode-specific errors
are reported properly, and not include lines that are added by
validation code (and thus don't get included in the editor's line count)
> Repaired and improved findSyntaxError function

- solutions/bonus/05_theCorridor.md
Override the trap's behaviour to do nothing
> Disabling traps

- solutions/bonus/AB_1_ANewJourney.md
Place 2 teleporters, one near the player and one near the exit (placing over a tree)
> Adding another solution for AB_1_ANewJourney.md

- solutions/bonus/soccer.md
Because I don't like solutions that override functions, even though they are unambiguously valid and it's the level author's duty to prevent them. Let's show a slightly less cheaty way it can be done.
> Add another solution to soccer.md

- scripts/validate.js
As suggested in #501. 
Don't have a strong opinion on whether this should be done, but I think it should at least be considered. Oh, and fixes #316.
> Don't disable tamper checking once super menu is enabled
