levels/19_documentObjectMadness.jsx

This pull request implements @mathdude314 's proposed changes, with a little cleanup, to fix `adversary` walking off the DOM and killing Dr. Eval.
It looks like a pull request was never made for this issue so I went ahead and made this one. I haven't tested this and I am just going off of what is mentioned in #331, so proceed with caution.

fix issue #331 for level 19

---

index.html
scripts/game.js
scripts/map.js

Now the drawingCanvas matches the size of the screen canvas. Deals with the canvas alignment issues in levels 16 and 17. Solves #329 (for me at least) on Safari and Chrome.

Fix issue with size of drawingCanvas

---

scripts/validate.js

This sequence can be used to escape arbitrary code and thus clearly needs to be forbidden.
Closes #378

Forbid `/u` escape sequence

---

scripts/validate.js

Closes #424. This pull request was made without comment as to whether this is actually a bug or an obscure but intended solution.

Ensure validation happens even if user code throws error

---

scripts/validate.js

Fixes a bug I introducted #428, which causes the game to not show mid-game exceptions at all in levels with the quickValidate option set (such as level 20).

Throw exceptions even on quickValidate levels

---

scripts/map.js
scripts/validate.js

This prevents levels with timers from causing an infinite stream of "Validation failed!" errors. If the timer is not cleared, then it will run, observe that validation still fails, and print another error, which repeats until the level is executed again or a new level starts.
Note that, unlike many of my other patches, this is not a security fix.

Clear timers after breaking level

---

levels/22_credits.jsx
scripts/game.js
scripts/map.js
scripts/reference.js
scripts/validate.js

The credits level, as currently coded, depends on the private attribute `map._display`. Access to the display was mostly broken by #433 (display is refreshed as a side effect of validation) and can lead to security issues so, as a predecessor to a future patch that blocks access to internal attributes, this rewrites the credits level
to no longer need that access, and also to work properly.

Rewrite credits level to not depend on private APIs

---

scripts/inventory.js
scripts/objects.js
scripts/player.js

The `game` object has no methods that are intended to be called from level code, and is not used in any `onCollision` or `onDrop` functions in any level. Passing it to `onCollision` and `onDrop` accomplishes nothing other than to create issues like #322.
Closes #322

Don't pass game into user code

---

scripts/dynamicObject.js
scripts/map.js
scripts/player.js
scripts/validate.js

Uses `Object.defineProperty` to prevent user code from attempting to read or write to the values of private attributes.

Prevent access to private attributes

---

scripts/objects.js

#444 means that just calling `obj._map`, which the previous code was doing, will crash with "Attempt to access private property eye._map". Rewrite the code to pass the map explicitly to avoid that error.

Fix error when eye would kill player in bonus levels

---

scripts/validate.js
solutions/20_bossFight.md

Applies the tamper-protection code I wrote in #447 to all functions of all objects instead of just a specified list of map and player functions:
In addition to being cleaner code, many of these methods are called by the game when `_playerCodeRunning` is false, meaning that any tampering with such a method will end up called without the game thinking player code is running, which is a bad idea for obvious reasons.

Generalize tamper prevention

---

scripts/validate.js

This was missed in #434 for some reason, however the same bug exists for the `objective` function.

Prevent tampering with objective function

---

scripts/dynamicObject.js
scripts/game.js
scripts/inventory.js
scripts/map.js
scripts/objects.js
scripts/player.js
scripts/validate.js

Specifically:
1.  The `onDeactivate` method of traps.
2. The `onCollision` method of dynamic objects that have just moved into the player (the player moving into the object was always called securely)
3. `validateLevel`, `onExit`, and `objective`.
4.  the `onDrop` and `onPickUp` methods of items
5.  the `onCollision` method of static objects

Fix several places where user code is called insecurely

---

scripts/validate.js

The `dummyMap._clearIntervals` call being moved here is necessary to prevent timers from firing at unwanted times, but it has the side effect of meaning that `validateNoTimers`, when run at the start of the level, does nothing. This PR fixes that bug by moving the `clearIntervals` call to be after validation, allowing validation to detect the number of timers properly.

Fix validation of timers in boss fight level

---

scripts/game.js
scripts/validate.js

This fixes "TypeError: this._eval is not a function", which would
sometimes occur when running a level. It also removes some redundant
code in scripts/game.js that sets `_eval` at level load that predates
using an iframe.

Cleanup eval handling

---

README.md
levels/bonus/01_inTheDesert.jsx
levels/bonus/02_theEmptyRoom.jsx
levels/bonus/03_theCollapsingRoom.jsx
levels/bonus/04_theGuard.jsx
levels/bonus/AB_1_ANewJourney.jsx
levels/bonus/AB_2_FrozenCave.jsx
levels/bonus/AB_3_BoulderMadness.jsx
levels/bonus/AB_4_BatAttack.jsx
scripts/game.js

When one level in the chain is solved, the next level is automatically loaded. This does not prevent the player from loading later levels
manually.

Add support for chains of bonus levels

---

scripts/game.js
scripts/inventory.js
scripts/objects.js

This bug happens when you complete a level, and then switched to either level 1 or a bonus level that explicitly places the computer on the map. The "level saved" message appears on top of the name of the music, rendering both pieces of text unreadable.

Fix "level saved" message rendering on top of music

---

levels/bonus/02_theEmptyRoom.jsx

If I return an undefined variable I won't die when I collide with the terminal.  I've added an additional test on lines 48-50 to prevent this.

prevent undefined objects

---

solutions/bonus/ice.md

Because the only listed solution to a level being using the super menu makes the impression that the level is impossible without cheating.

Add another solution to ice.md

---

solutions/bonus/AB_1_ANewJourney.md

Because the other two solutions both feel like cheats, even though they're unquestionably valid.

Add another solution to AB_1_ANewJourney.md

---

scripts/player.js

Fixes #159, and also an unreported bug where dying in some levels (such as level 10) would produce a bogus error message to the console upon reload.

Fix death workflow

---

levels/bonus/DOMchase.jsx

This was originally intended to be an update to level 19 to resolve #65. I decided it was better as a bonus level at this stage in the game's lifecycle. I seem to have never got around to posting it when I wrote it in 2019 and was reminded of it now so resurrected it.
The level is technically trivial (the solution is just `preferBack = isAtTopLevel` and then chase the adversary through the entire DOM), but realizing that is difficult (the structure of the DOM means that preferBack = true loops indefinitely in the class table and preferBack = false loops between the class table and the Cicero quote)
My comment in #142 was referring to a more complicated version of this level where there were multiple sub-line editable sections each of which was too short to write the words `isAtTopLevel` …

Add a DOM bonus level

---

levels/bonus/02_theEmptyRoom.jsx

Reverts AlexNisnevich/untrusted#471
To fix #514
And because this was added by a later user not the original author of the level whereas the spirit of the game says it's up to the level author(s) to deal with unintended solutions.

Revert "prevent undefined objects"
